name: "Class Struggle"
url: "https://outsorcerer.github.io/class-struggle/"
title: "Class Struggle"
author:
  name: "Evgeniy Mamchenko"
  email: evgeniy.mamchenko@yandex.ru
description: "A blog about programming and machine learning and how they are changing the world."
copyright: "(c) Evgeniy Mamchenko, 2017"
encoding: utf-8
baseurl: "/class-struggle"
theme: jekyll-theme-cayman
